spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: #
    username: #
    password: #
    initialization-mode: always
    platform: mysql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

