spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/test1
    username: admin
    password: admin
    #initialization-mode: always
    #platform: mysql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
